version: "3.9"

services:
  flask_app:
    container_name: "web"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - flask_db
  flask_db:
    container_name: "database"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Namixluffy123#
      MYSQL_DATABASE: ariadnePOC
    ports:
      - "3307:3307"